import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`min-h-screen flex flex-col antialiased`}>
                <header className="border-b p-4">E-Commerce</header>
                <main className="flex-1 container mx-auto px-4">
                    {children}
                </main>
                <footer className="border-t p-4 text-center text-sm">
                    © 2025
                </footer>
            </body>
        </html>
    );
}
