import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/lib/cart-context";
import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`min-h-screen flex flex-col antialiased`}>
                <CartProvider>
                    <Navbar />
                    <main className="flex-1 container mx-auto px-4">
                        {children}
                    </main>
                </CartProvider>
            </body>
        </html>
    );
}
